spring:
  datasource:
    url: jdbc:h2:mem:massiver
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # H2 ?? ???
      path: /h2-console  # H2 ?? ?? ??
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # ?????? ?? ? ??? ?? ????
    show-sql: true  # SQL ?? ?? ???
server:
  port: 2025
